import assert from 'node:assert/strict'
import { mkdirSync, mkdtempSync, readdirSync, renameSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { build } from 'esbuild'

// Both modules are bundled the way the app would: store.ts against a stub `electron` whose every
// path is a throwaway folder (so nothing here can reach a real data folder), Notes.tsx as-is.
const here = (p) => fileURLToPath(new URL(p, import.meta.url))
const bundle = async (entry, plugins = []) => {
  const { outputFiles } = await build({
    entryPoints: [here(entry)],
    bundle: true, write: false, platform: 'node', format: 'esm', jsx: 'automatic', tsconfig: here('../tsconfig.web.json'), logLevel: 'silent', plugins,
  })
  return import(`data:text/javascript;base64,${Buffer.from(outputFiles[0].text).toString('base64')}`)
}
const electron = {
  name: 'electron',
  setup: (b) => {
    b.onResolve({ filter: /^electron$/ }, () => ({ path: 'electron', namespace: 'stub' }))
    b.onLoad({ filter: /.*/, namespace: 'stub' }, () => ({ contents: 'export const app = { getPath: () => globalThis.__userData }' }))
  },
}

// --- store: version throttle, Google Doc stubs, tags ---
const userData = mkdtempSync(path.join(tmpdir(), 'tartan-notes-'))
const data = path.join(userData, 'data')
globalThis.__userData = userData
writeFileSync(path.join(userData, 'config.json'), JSON.stringify({ dataDir: data }))
const { loadConfig, writeNote, listVersions, readVersion, searchNotes, noteIndex } = await bundle('../src/main/store.ts', [electron])
loadConfig()

// Autosave fires every 600 ms while typing; one snapshot per five minutes is the intent.
for (const text of ['one', 'two', 'three', 'four']) await writeNote('a.md', text)
assert.equal((await listVersions('a.md')).length, 1)
// ...and a snapshot older than that no longer blocks the next one.
const dir = path.join(data, '.versions', 'a.md')
for (const f of readdirSync(dir)) renameSync(path.join(dir, f), path.join(dir, '2020-01-01T00-00-00.000Z.md'))
await writeNote('a.md', 'five')
assert.equal((await listVersions('a.md')).length, 2)

// A restore writes an old text over the current one: what it replaces must be recoverable even
// though a snapshot was taken seconds ago.
const tick = () => new Promise((r) => setTimeout(r, 5))
for (const text of ['A', 'B', 'C', 'D']) await writeNote('r.md', text)
assert.equal((await listVersions('r.md')).length, 1)
await tick()
await writeNote('r.md', 'A', true)
const afterRestore = await listVersions('r.md')
assert.equal(afterRestore.length, 2)
assert.equal(await readVersion('r.md', afterRestore[0].stamp), 'D')
// Cutting the note to under half its length (select-all-delete) is snapshotted the same way;
// an ordinary small edit inside the window is not.
const long = 'x'.repeat(100)
await writeNote('s.md', long)
await writeNote('s.md', long + '1')
await writeNote('s.md', long + '12')
assert.equal((await listVersions('s.md')).length, 1)
await tick()
await writeNote('s.md', '')
const afterCut = await listVersions('s.md')
assert.equal(afterCut.length, 2)
assert.equal(await readVersion('s.md', afterCut[0].stamp), long + '12')
// Cut, retype, cut again: the second cut would snapshot text the newest snapshot already holds.
await writeNote('b.md', long)
await writeNote('b.md', '')
await writeNote('b.md', long)
await tick()
await writeNote('b.md', '')
assert.equal((await listVersions('b.md')).length, 1)
// A cut of a 10-character note is not worth bypassing the throttle.
for (const text of ['one', 'two', 'abcdefghij', 'x']) await writeNote('t.md', text)
assert.equal((await listVersions('t.md')).length, 1)

// A Drive stub is JSON, not writing: searchable by title only, and its email never shows.
mkdirSync(path.join(data, 'notes', 'c'), { recursive: true })
writeFileSync(path.join(data, 'notes', 'c', 'Lecture Doc.gdoc'), '{"doc_id":"abc123","email":"someone@gmail.com","": "WARNING! DO NOT EDIT THIS FILE!"}')
assert.deepEqual(await searchNotes('gmail'), [])
assert.deepEqual(await searchNotes('warning'), [])
const byTitle = await searchNotes('lecture')
assert.equal(byTitle.length, 1)
assert.equal(byTitle[0].snippet, '')

// The tag the chip shows is the tag the index holds; `#include` in code is C, not a tag.
await writeNote('t.md', '#exam and #nested/tag\n\n```c\n#include <stdio.h>\n```\n\nuse `#inline` here, see http://x.com/#frag\n')
const tags = (await noteIndex()).find((n) => n.path === 't.md').tags
assert.deepEqual(tags, ['exam', 'nested/tag'])

// The window may only show the app's own page: links go to the browser, everything else is dropped.
const { navDecision } = await bundle('../src/main/nav.ts')
const page = 'file:///C:/app/out/renderer/index.html'
assert.equal(navDecision(page, page), 'allow')
assert.equal(navDecision(page + '#notes', page), 'allow')
assert.equal(navDecision('https://www.cmu.edu/', page), 'external')
assert.equal(navDecision('http://example.com/a', page), 'external')
for (const url of ['file:///C:/Windows/win.ini', 'javascript:alert(1)', 'data:text/html,<h1>x</h1>']) assert.equal(navDecision(url, page), 'block', url)

// --- renderer: dollars, raw head tags, chips ---
const { renderBody, quoteHead } = await bundle('../src/renderer/src/views/Notes.tsx')
const none = new Map()
const plain = renderBody('I paid $5 and then $10 for lunch.', none)
assert.ok(plain.includes('$5 and then $10') && !plain.includes('katex'))
assert.ok(renderBody('Escaped: \\$5 and \\$10 here.', none).includes('Escaped: $5 and $10 here.'))
assert.ok(renderBody('about $5, but $x^2$ is math', none).match(/class="katex"/g).length === 1)
assert.ok(renderBody('$$y$$', none).includes('katex-display'))
assert.ok(!renderBody('a $ b and c $ d', none).includes('katex'))
for (const t of ['$20,000 and $30,000', 'between $5 and $10', 'take $1 or $2']) assert.ok(!renderBody(t, none).includes('katex'), t)
for (const t of ['$2x$', '$0$', '$2^n$', '$3x+1$']) assert.ok(renderBody(t, none).includes('class="katex"'), t)
for (const evil of [
  '<meta http-equiv="refresh" content="0;url=https://example.com/">\n\nhi',
  '<<meta>meta http-equiv="refresh" content="0;url=https://example.com/">',
  '<base href="https://example.com/">\n\nhi',
  '<META HTTP-EQUIV=refresh CONTENT="0;url=https://example.com/"',
]) assert.ok(!/<\s*(meta|base)/i.test(renderBody(evil, none)), evil)
assert.ok(renderBody('see #nested/tag', none).includes('data-tag="nested/tag"'))
assert.ok(renderBody('[cmu](https://www.cmu.edu/)', none).includes('<a href="https://www.cmu.edu/">'))
// A quote goes after a blank line when the note has text, and at the very top when it is empty.
assert.equal(quoteHead('', 'to be'), '> to be  (p. ')
assert.equal(quoteHead(' \n\n', 'to be'), '> to be  (p. ')
assert.equal(quoteHead('Notes so far.\n\n', 'to be'), 'Notes so far.\n\n> to be  (p. ')
rmSync(userData, { recursive: true, force: true })
console.log('Notes: version throttle and forced snapshots, Google Doc search, tag index, navigation guard, dollar amounts and raw head tags checks passed.')
